Youtube Project - First Pull Request
tiagoes/youtubeProject pull request #2
Opened 2020-06-04 13:25 UTC by tiagoes

Please review our first Project

2020-06-05 02:05 UTC, HADDADSOHAIB requested changes
> ### Pull Request under the review by Sohaib Haddad. (TSE)
### Change Required :recycle: 

### Hello @tiagoes and @defoebrand   :handshake: 

### Good job so far :clap:  your project is looking good :medal_sports: 

### there are some changes to get the project approved :point_down:
- I think your readme could be improved, the readme file should be descriptive, add more information about the project and fix the live demo link, it is not working (suggesting: use http://raw.githack.com/ to generate a live link)
- Your pull request description could also be improved, always remember to be descriptive, write what you did in your feature and what this pull request is adding, take a look at this link to understand why a GitHub repository should look professional:
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
- You should check the project with the validator and fix the issues:
- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. (Students were asked to use this one, so in most cases their code should be already validated) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
![Screenshot from 2020-06-05 02-40-25](https://user-images.githubusercontent.com/26064042/83827366-1b552b00-a6d6-11ea-95e4-d7249e721aca.png)
- Your css file needs to be improved, take a second look at this article and try to avoid bad practice in your code:
- [x] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
check the comments for additional explanation.
- The search bar should be centered:
- [x] The search bar is aligned to the middle of the navbar ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/searchbar_align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
- the share and subscribe should be buttons:
- [x] It has a share button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
- [x] It has a subscribe button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
### Please do the changes and ask for another code review :+1:

2020-06-05 02:05 UTC, HADDADSOHAIB commented on index.css
> +  /**/
Delete unnecessary comments to keep your code clean.

2020-06-05 02:05 UTC, HADDADSOHAIB commented on index.css
> +  /* border: 1px solid black; */
Delete commented code:
- [ ] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-06-05 02:05 UTC, HADDADSOHAIB commented on index.css
> +  display: flex;
also here delete commented code:
- [ ] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-06-05 09:06 UTC, tiagoes commented
**We made the requested changes:** 

Increased the description in the readme file.
Fix the Live link.
We checked the HTML market with the validator 
Deleted excess comments in CSS.
Center aligned the search bar.
Made Share and Subscribe a button.

2020-06-06 00:08 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @tiagoes & @defoebrand  :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
Please makes changes and submit another review request.

- [ ] Delete all the necessary branches in this repo they are cluttering your awesome project's repo.
- [ ] The markup is still showing some error in the validator. Kindly fix that, thank you.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-08 08:23 UTC, tiagoes commented
We made the requested changes:
We correct the error showed in the Markup
We deleted the extra git branches

2020-06-08 09:22 UTC, peterrobert commented
### PULL REQUEST UNDER REVIEW BY PETER ROBERT

2020-06-08 09:28 UTC, peterrobert approved these changes
### APPROVED :+1: 
Great job. your project looks exactly like the clone :+1: a wonderful job . Great job implementing the suggested changes.
**on to the next project**
### HAPPY CODING

2020-06-22 14:03 UTC, merged